
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring-hack
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8888